name: website
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.7
  - ipykernel=5.1.3
  - jupyterlab=1.1.4
  - matplotlib
  - seaborn
  - pandas=0.25.1
  - numpy
  - scikit-learn
  - pip=19.2.3
  - nb_conda_kernels=2.2.2
  - pylint
  - click
  - black
  - flake8
  - tqdm

  - pip:
    - pre-commit==1.18.3

    - nbsphinx==0.4.2
    - pytest==5.2.0
    - pytest-cov==2.7.1
    - pytest-pythonpath==0.7.3

    - sphinx==2.2.0
    - sphinx-autobuild==0.7.1
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-bibtex==1.0.0
